In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

1.13.0
Using device: cuda
MPS device not found.


In [13]:
# for windows
# just don't run this cell on mac

torch.cuda.set_device(cuda)


In [5]:
## intro to tensors

# what is a tensor? a multidimensional matrix

# first tensor is called a scalar

# creating a scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# what are some attributes of a scalar (tensor)?

# what are the dimensions of a scalar?
# 0, a scalar has no dimensions

scalar.ndim

# use the .item() method to conver to regular python int

scalar.item()

7

In [7]:
# vectors

# a vector has magnitude and direction

# this is a one dimensional array, or single column of numbers

vector = torch.tensor([7, 5])
vector

tensor([7, 5])

In [9]:
# dimension can be interpreted as number of sets of square brackets in the input

print(vector.ndim)

# whereas shape is more like how a traditional matrix or vector would be described. 
# in this case, our shape is 2, as this is a 2x1 matrix, or 2 rows and 1 column

print(vector.shape)


1
torch.Size([2])


In [10]:
# matrices

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# accessing matrix elements

# first element
MATRIX[0]

# second element
MATRIX[1]

tensor([ 9, 10])

In [15]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,3,4]]])

TENSOR.ndim

3

In [25]:
print(TENSOR.shape)

# ah ok, shape is saying that we have a single 3x3 matrix as an entry
# the 1 is the outer most square bracket pair
# the first 3 is the middle bracket pair
# the second 3 is the inner most bracket pair.

# the 0th position returns the whole matrix

print(TENSOR[0]) # first position accesses entire matrices
print(TENSOR[0][0]) # second position accesses a single vector
print(TENSOR[0][0][0]) # third position accesses a single entry in a single vector

# had to refer to torch.tensor docs to find how to index each position

torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 3, 4]])
tensor([1, 2, 3])
tensor(1)


 Why random tensors?

 Random tensors are important because the way many neural networks learn, is that they start with tensors full of random numbers and then adjust those random numbers to better reporesent the data.

 `Start with rand -> look at data - > update randoms -> look at data -> update rand`

In [42]:
# random tensors

# create a random tensor 3x4 matrix

random_tensor = torch.rand(3,4)
random_tensor

random_tensor2 = torch.rand(10,10)
random_tensor2

random_tensor3 = torch.rand(10,10,10)
random_tensor3

tensor([[[0.8144, 0.8476, 0.8275, 0.1274, 0.6850, 0.6554, 0.3450, 0.6684,
          0.1537, 0.9001],
         [0.9156, 0.8499, 0.1184, 0.0431, 0.3045, 0.8486, 0.9557, 0.7218,
          0.8339, 0.2257],
         [0.0792, 0.8869, 0.6376, 0.7461, 0.1639, 0.4361, 0.5063, 0.7830,
          0.7082, 0.9096],
         [0.4722, 0.7653, 0.5538, 0.6373, 0.9540, 0.9732, 0.7193, 0.3754,
          0.5991, 0.8093],
         [0.6684, 0.0980, 0.3968, 0.0049, 0.9773, 0.9883, 0.9753, 0.9432,
          0.4866, 0.7618],
         [0.5886, 0.6614, 0.1053, 0.3555, 0.8871, 0.6265, 0.4651, 0.6261,
          0.2249, 0.7045],
         [0.5462, 0.8734, 0.7200, 0.3934, 0.0924, 0.3153, 0.5801, 0.0394,
          0.1425, 0.7789],
         [0.9110, 0.4086, 0.1287, 0.0456, 0.9676, 0.2285, 0.8430, 0.1439,
          0.3022, 0.5723],
         [0.7032, 0.3962, 0.1903, 0.0392, 0.6984, 0.8365, 0.0950, 0.0220,
          0.0400, 0.5681],
         [0.2480, 0.8981, 0.9415, 0.6179, 0.2003, 0.2167, 0.6314, 0.3835,
          0.4789,

In [38]:
random_tensor.ndim

2

In [40]:
random_tensor2.ndim

2

In [43]:
random_tensor3.ndim

3

In [44]:
# create a random tensor with similar shape to an image tensor

rand_img_size_tensor = torch.rand(size = (224,224,3)) # height, width, colour channel
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)