In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

c:\Users\Aaron\anaconda3\envs\torch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.13.0
Using device: cuda
MPS device not found.


In [3]:
# tensor error types

# 1. not right datatype
# 2. not correct shape
# 3. not on correct device

In [9]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float32,
                                device=device,
                                requires_grad=False)

In [10]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [11]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [15]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long, device=device)
int_32_tensor

tensor([3, 6, 9], device='mps:0')

In [16]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='mps:0')